// Copyright Information
// ==================================
// AutoLot-WebApps - AutoLot.Models - BaseEntity.cs
// All samples copyright Philip Japikse
// http://www.skimedic.com 2026/09/07
// ==================================

namespace AutoLot.Models.Entities.Base;

/// <summary>
///     Represents the base entity for all models.
/// </summary>
/// <remarks>
///     Contains the primary key and timestamp for concurrency.
/// </remarks>
public abstract class BaseEntity
{
    /// <summary>
    ///     The primary key for the entity.
    /// </summary>
    /// <remarks>
    ///     This value is generated by the database.
    /// </remarks>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     The timestamp used for concurrency checks.
    /// </summary>
    /// <remarks>
    ///     This value is managed by the database.
    /// </remarks>
    [Timestamp]
    public long TimeStamp { get; set; }
}